# Generated by Django 4.2.13 on 2026-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.CharField(choices=[('survey', 'Site Survey ($80)'), ('drilling', 'Borehole Drilling'), ('install_electric', 'Borehole Installation – Electric ($1,900)'), ('install_solar', 'Borehole Installation – Solar ($2,000)'), ('solar_1kva', 'Solar System – 1KVA ($650)'), ('solar_3kva', 'Solar System – 3KVA ($850)'), ('solar_6kva', 'Solar System – 6.2KVA ($1,500)'), ('solar_10kva', 'Solar System – 10KVA ($3,150)'), ('repair', 'Borehole Repairs / Flushing'), ('pump_fishout', 'Pump Fishout'), ('assessment', 'Assessment'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('quoted', 'Quoted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
