# Generated by Django 4.2.13 on 2026-03-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoreholeAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='per meter', max_length=30)),
                ('icon', models.CharField(default='🔩', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('survey', 'Site Survey'), ('borehole', 'Borehole Drilling'), ('installation', 'Borehole Installation'), ('solar', 'Solar System'), ('repair', 'Repairs & Maintenance'), ('assessment', 'Assessment')], max_length=20)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='⚙️', help_text='Emoji icon', max_length=10)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_label', models.CharField(blank=True, help_text='e.g. "from $160" or "call for price"', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('survey', 'Site Survey'), ('borehole', 'Borehole Drilling'), ('installation', 'Borehole Installation'), ('solar', 'Solar System'), ('repair', 'Repairs & Maintenance'), ('assessment', 'Assessment')], default='solar', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('kva_label', models.CharField(blank=True, max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labour_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('features', models.TextField(help_text='One feature per line')),
                ('powers', models.TextField(blank=True, help_text='What appliances it can power')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.service')),
            ],
            options={
                'ordering': ['order', 'base_price'],
            },
        ),
    ]
